export type SectionId = "research" | "model" | "generation" | "agent" | "subagent" | "context" | "embedding" | "multimodal" | "advanced";
export interface SettingResult { section: SectionId; label: string; description: string; anchor: string; keywords: string; }
export function settingAnchor(label: string): string { return label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
/** Index labels and explanations only: credentials and live input values are never searched. */
export const SETTINGS_INDEX: SettingResult[] = [
  { section: "model", label: "ChatGPT subscription", description: "Sign in with ChatGPT and view your Codex usage allowance and reset times.", anchor: "chatgpt-subscription", keywords: "openai authentication oauth login subscription limits quota usage sign out" },
  {"section": "model", "label": "Provider", "description": "", "anchor": "provider", "keywords": ""},
  {"section": "model", "label": "API", "description": "", "anchor": "api", "keywords": ""},
  {"section": "model", "label": "Model", "description": "", "anchor": "model", "keywords": ""},
  {"section": "model", "label": "Endpoint", "description": "Optional full URL override for the chat endpoint — an Azure OpenAI deployment, a corporate proxy, or a local OpenAI-compatible server (Ollama, LM Studio, vLLM). Blank uses the provider's official endpoint. Model listing still uses the official catalog; with an unreachable catalog the built-in model list applies.", "anchor": "endpoint", "keywords": ""},
  {"section": "model", "label": "OpenRouter Headers", "description": "Optional. Controls which site is credited in the OpenRouter dashboard and usage stats.", "anchor": "openrouter-headers", "keywords": ""},
  {"section": "model", "label": "Provider Routing", "description": "Optional. Controls which upstream providers OpenRouter routes this model to, and in what order.", "anchor": "provider-routing", "keywords": ""},
  {"section": "model", "label": "Allow fallback providers", "description": "", "anchor": "allow-fallback-providers", "keywords": ""},
  {"section": "generation", "label": "Temperature", "description": "", "anchor": "temperature", "keywords": ""},
  {"section": "generation", "label": "Max Tokens", "description": "", "anchor": "max-tokens", "keywords": ""},
  {"section": "generation", "label": "Unlimited", "description": "", "anchor": "unlimited", "keywords": ""},
  {"section": "generation", "label": "Effort", "description": "How much work the model puts into a turn — thinking depth, token spend, and tool-calling eagerness. Applies whether or not thinking is on.", "anchor": "effort", "keywords": ""},
  {"section": "generation", "label": "Reasoning Effort", "description": "Depth levels follow the selected model — newer GPT-5.x models add shallower (none/minimal) and deeper (x-high) rungs.", "anchor": "reasoning-effort", "keywords": ""},
  {"section": "generation", "label": "Service Tier", "description": "", "anchor": "service-tier", "keywords": ""},
  {"section": "generation", "label": "Cache TTL", "description": "How long a prompt-cache breakpoint stays warm. Defaults to 1h, since a real session routinely has gaps over 5 minutes that would otherwise miss the cache entirely and get rewritten at the write premium. 5m only pays off for rapid back-to-back turns with no gaps.", "anchor": "cache-ttl", "keywords": ""},
  {"section": "generation", "label": "Fast Mode", "description": "Beta. Runs this model at up to 2.5x higher output tokens/sec, at premium pricing. First-party Anthropic API only.", "anchor": "fast-mode", "keywords": ""},
  {"section": "generation", "label": "Enable fast mode", "description": "", "anchor": "enable-fast-mode", "keywords": ""},
  {"section": "generation", "label": "Task Budget", "description": "Beta. Gives the model a self-paced token ceiling for an agentic loop instead of an enforced per-response cut-off. Minimum 20,000 (clamped up). Blank disables it.", "anchor": "task-budget", "keywords": ""},
  {"section": "generation", "label": "Context Editing", "description": "Beta. Clears stale tool_use/tool_result content server-side before the model sees it, keeping the effective prompt lean without summarizing.", "anchor": "context-editing", "keywords": ""},
  {"section": "generation", "label": "Enable context editing", "description": "", "anchor": "enable-context-editing", "keywords": ""},
  {"section": "generation", "label": "Server-Side Compaction", "description": "", "anchor": "server-side-compaction", "keywords": ""},
  {"section": "generation", "label": "Refusal Fallback", "description": "Beta. This model's safety classifiers may decline a request; on by default, this retries a declined turn on Anthropic's recommended substitute — chosen per refusal category — within the same request, instead of ending the run.", "anchor": "refusal-fallback", "keywords": ""},
  {"section": "generation", "label": "Enable refusal fallback", "description": "", "anchor": "enable-refusal-fallback", "keywords": ""},
  {"section": "generation", "label": "Responses API", "description": "Uses OpenAI's Responses API instead of Chat Completions. Preserves this model's internal reasoning state across tool-call round trips, instead of re-reasoning from scratch every turn — most valuable for multi-step tool-heavy tasks. No effect on non-reasoning models.", "anchor": "responses-api", "keywords": ""},
  {"section": "generation", "label": "Enable Responses API", "description": "", "anchor": "enable-responses-api", "keywords": ""},
  {"section": "agent", "label": "Max Iterations", "description": "Maximum agent tool-loop rounds before stopping.", "anchor": "max-iterations", "keywords": ""},
  {"section": "agent", "label": "Spending", "description": "Spend is estimated from provider/model pricing after each billed response. A hard stop prevents another tool/model round once the observed total reaches the ceiling; the response that crosses it has already been billed. Unknown pricing is shown as partial and cannot be hard-enforced.", "anchor": "spending", "keywords": "budget spending cost limit"},
  {"section": "agent", "label": "Session ceiling (USD)", "description": "", "anchor": "session-ceiling-usd", "keywords": "budget spending cost limit"},
  {"section": "agent", "label": "Warning threshold", "description": "", "anchor": "warning-threshold", "keywords": ""},
  {"section": "agent", "label": "Stop at ceiling", "description": "", "anchor": "stop-at-ceiling", "keywords": "budget spending cost limit"},
  {"section": "agent", "label": "Delegated Subagents", "description": "Lets the agent spin off self-contained subtasks to independent subagents — their own conversation and tool budget — for parallelism and to keep the main conversation's context focused. Each delegated lane is extra token spend on top of the main conversation. Turn off to keep every token in this one conversation when cost efficiency matters most.", "anchor": "delegated-subagents", "keywords": ""},
  {"section": "agent", "label": "Allow delegating to subagents", "description": "", "anchor": "allow-delegating-to-subagents", "keywords": ""},
  {"section": "agent", "label": "Tool Access", "description": "", "anchor": "tool-access", "keywords": ""},
  {"section": "agent", "label": "Agent Memory", "description": "", "anchor": "agent-memory", "keywords": ""},
  {"section": "agent", "label": "Enable memory index", "description": "", "anchor": "enable-memory-index", "keywords": ""},
  {"section": "subagent", "label": "Subagent Provider", "description": "Override which provider and model runs in delegated lanes. 'Inherit' uses the parent session's provider.", "anchor": "subagent-provider", "keywords": ""},
  {"section": "subagent", "label": "Max Concurrent Lanes", "description": "Maximum parallel subagent lanes per turn (1–8). Default: 4.", "anchor": "max-concurrent-lanes", "keywords": ""},
  {"section": "subagent", "label": "Concurrent limit", "description": "", "anchor": "concurrent-limit", "keywords": ""},
  {"section": "subagent", "label": "Profiles", "description": "", "anchor": "profiles", "keywords": ""},
  {"section": "research", "label": "Allowed domains", "description": "One hostname per line, including its subdomains. Workspace lists replace the user list. Only this confirmation grants new access.", "anchor": "allowed-domains", "keywords": ""},
  {"section": "research", "label": "Denied domains", "description": "Denies override every matching grant.", "anchor": "denied-domains", "keywords": ""},
  {"section": "research", "label": "Unknown domains", "description": "", "anchor": "unknown-domains", "keywords": ""},
  {"section": "research", "label": "Search provider", "description": "Enabling Brave authorizes sending reviewed queries to its API. Source-domain grants are separate.", "anchor": "search-provider", "keywords": ""},
  {"section": "research", "label": "Brave API key", "description": "", "anchor": "brave-api-key", "keywords": ""},
  {"section": "research", "label": "Browser approval reviewer", "description": "Human review is the default. Delegation applies only to this chat session and never includes new domains, scripts or consequential actions. Uses the current configured provider in a separate no-tools call.", "anchor": "browser-approval-reviewer", "keywords": ""},
  {"section": "context", "label": "History Compression", "description": "", "anchor": "history-compression", "keywords": " compaction history context"},
  {"section": "context", "label": "Enable compression", "description": "", "anchor": "enable-compression", "keywords": ""},
  {"section": "context", "label": "Compaction mode", "description": "Background keeps working while history compresses. Pause waits for the summary before the next model call. Stop remains available.", "anchor": "compaction-mode", "keywords": ""},
  {"section": "context", "label": "Trigger At", "description": "% of the context window that triggers compression.", "anchor": "trigger-at", "keywords": ""},
  {"section": "context", "label": "Keep Recent", "description": "Messages kept verbatim after compression.", "anchor": "keep-recent", "keywords": ""},
  {"section": "context", "label": "Compression Model", "description": "Optional — leave blank to use the active model. A faster/cheaper model can be used for compression.", "anchor": "compression-model", "keywords": " compaction history context"},
  {"section": "embedding", "label": "Embedding Model", "description": "", "anchor": "embedding-model", "keywords": ""},
  {"section": "embedding", "label": "Embedding Provider", "description": "", "anchor": "embedding-provider", "keywords": ""},
  {"section": "embedding", "label": "Model", "description": "Dimensions are fixed per model. Changing the model or dimensions invalidates existing vectors — rebuild after switching.", "anchor": "model", "keywords": ""},
  {"section": "embedding", "label": "Rebuild Index", "description": "Clears vectors embedded under the previous model so search stays correct. The agent memory index re-populates as the agent works; re-import Data workbench collections to re-embed them.", "anchor": "rebuild-index", "keywords": ""},
  {"section": "multimodal", "label": "Attachment routing", "description": "", "anchor": "attachment-routing", "keywords": ""},
  {"section": "multimodal", "label": "Image fallback", "description": "", "anchor": "image-fallback", "keywords": ""},
  {"section": "multimodal", "label": "Fallback provider", "description": "", "anchor": "fallback-provider", "keywords": ""},
  {"section": "multimodal", "label": "Vision-capable model", "description": "Only models the catalog reports as vision-capable are shown.", "anchor": "vision-capable-model", "keywords": ""},
  {"section": "multimodal", "label": "Audio transcription bridge", "description": "", "anchor": "audio-transcription-bridge", "keywords": ""},
  {"section": "multimodal", "label": "Transcribe attached audio", "description": "", "anchor": "transcribe-attached-audio", "keywords": ""},
  {"section": "multimodal", "label": "OpenAI key", "description": "", "anchor": "openai-key", "keywords": ""},
  {"section": "multimodal", "label": "Transcription model", "description": "", "anchor": "transcription-model", "keywords": ""},
  {"section": "multimodal", "label": "Language hint", "description": "Optional, for example en or es. Leave blank for automatic detection.", "anchor": "language-hint", "keywords": ""},
  {"section": "advanced", "label": "Execution Logs", "description": "", "anchor": "execution-logs", "keywords": ""},
  {"section": "advanced", "label": "API Keys", "description": "", "anchor": "api-keys", "keywords": ""},
  {"section": "advanced", "label": "VS Code Settings", "description": "", "anchor": "vs-code-settings", "keywords": ""},
  {"section": "model", "label": "Credentials and API keys", "description": "Connect your provider or configure AWS credentials.", "anchor": "", "keywords": "authentication token secret bedrock"},
  {"section": "subagent", "label": "Subagent provider and model", "description": "Choose the provider and model used by delegated agents.", "anchor": "", "keywords": "delegation specialist"},
];
export function searchSettings(query: string): SettingResult[] {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (!terms.length) return [];
  return SETTINGS_INDEX.filter((entry) => {
    const text = `${entry.label} ${entry.description} ${entry.keywords}`.toLowerCase();
    return terms.every((term) => text.includes(term));
  }).sort((a, b) => Number(b.label.toLowerCase().includes(query.toLowerCase().trim())) - Number(a.label.toLowerCase().includes(query.toLowerCase().trim())));
}
